---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-back-end-api-app
  namespace: tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-back-end-api-app
      role: admin-back-end-api
  template:
    metadata:
      labels:
        app: admin-back-end-api-app
        role: admin-back-end-api
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-back-end-api-app
  namespace: tenant
  labels:
    app: admin-back-end-api-app
    role: admin-back-end-api
spec:
  selector:
    app: admin-back-end-api-app
    role: admin-back-end-api
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP