---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-app
  namespace: tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end-app
      role: front-end
  template:
    metadata:
      labels:
        app: front-end-app
        role: front-end
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-app
  namespace: tenant
  labels:
    app: front-end-app
    role: front-end
spec:
  selector:
    app: front-end-app
    role: front-end
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP