---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alice-admin
  namespace: tenant
subjects:
- kind: ServiceAccount
  name: alice
  namespace: tenant
  apiGroup: ""
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io