---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secops-engineer
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]